### ISSUE TITLE
Regional/Dialect language tag not supported

### ISSUE THREAD

**Issue by ubald** [TAPevents/tap-i18n#102]
My app supports english and french (en & fr).

But when doing (passing the window.navigator.language value for example):

```
TAPi18n.setLanguage('en-CA'); // Or en-US, en-UK, fr-FR, fr-CA...
```

It fails saying that the language is not supported. I should not have to create a file or list all the variants manually. It should use the file if I have it, otherwise fallback to the "main" en/fr language file.

**Comment by ubald** [comment]
I think https://github.com/TAPevents/tap-i18n/pull/103 should fix this issue.

**Comment by theosp** [comment]
Thanks for reporting.

A robust fix is indeed needed here to make tap:i18n work as it should for dialects.

#103 fix your symptom and is good as it enriches our languages names list but doesn't really fix the cause.
